name: EvNav

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  curved_labeled_navigation_bar: ^2.0.2 #latest version
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3 # Check for the latest version
  location: ^5.0.3
  geolocator: ^7.6.2
  geocoding: ^2.1.0
  flogger: ^0.0.8
  # Fire base dependenies for Real Time DB integration
  firebase_core: ^2.7.1
  firebase_core_web: ^2.10.0
  firebase_database: ^10.4.0
  firebase_auth: ^4.17.3
  google_sign_in: ^6.2.1
  syncfusion_flutter_maps: ^24.1.46
  flutter_svg: ^2.0.9
  flutter_polyline_points: ^2.0.0
  auto_size_text: ^3.0.0
  http: ^1.2.0
  google_nav_bar: ^5.0.6
  firebase_storage: ^11.6.5
  image_picker: ^1.0.7
  cloud_firestore: ^4.15.4
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  maps_launcher: ^2.2.1
  random_uuid_string: ^0.0.2
  permission_handler: ^11.3.1
  favorite_button: ^0.0.4
  animations: ^2.0.11
  # connectivity_plus: ^6.0.3
  get: ^4.6.6
  animated_text_kit: ^4.2.2
  intl: ^0.19.0
  awesome_dialog: ^3.2.0
  cool_alert: ^2.0.1

  file_picker: ^8.0.0+1
  path_provider: ^2.1.3
  fluttertoast: ^8.0.8
  syncfusion_flutter_pdf: ^24.2.6
  universal_html: ^2.2.4
  loading_animation_widget: ^1.2.1
  connectivity: ^3.0.6
  rive: ^0.13.4
  animated_snack_bar: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pin-point_9537049.png"
  flutter_lints: ^2.0.0
  animate_do: ^3.3.3
  auto_size_text: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/carSelectionImages/
    - assets/Intro/
